# Generated by Django 4.1.6 on 2023-05-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usergroups')),
            ],
        ),
        migrations.CreateModel(
            name='noteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes')),
            ],
        ),
        migrations.CreateModel(
            name='noteStudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes')),
            ],
        ),
        migrations.CreateModel(
            name='noteDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes')),
            ],
        ),
    ]
