# Generated by Django 4.1.6 on 2023-05-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_usernotes_notesummary_notestudymaterial_notedeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedeadline',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes', unique=True),
        ),
        migrations.AlterField(
            model_name='notestudymaterial',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes', unique=True),
        ),
        migrations.AlterField(
            model_name='notesummary',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes', unique=True),
        ),
    ]
