# Generated by Django 4.1.6 on 2023-05-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_notedeadline_note_alter_notestudymaterial_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedeadline',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes'),
        ),
        migrations.AlterField(
            model_name='notestudymaterial',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes'),
        ),
        migrations.AlterField(
            model_name='notesummary',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usernotes'),
        ),
    ]
